services:

  postgres:
    image: postgres:14
    container_name: postgres_container
    environment:
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_NAME
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}'"]
      interval: 10s
      timeout: 3s
      retries: 3

  ghelephant:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["-s", "${START_DATE}", -e, "${END_DATE}", "-i"]
    environment:
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATA_PATH ${DATA_PATH}
      - SED_NAME=${SED_NAME}

volumes:
  postgres_data:

networks:
  postgres_network:
